events {}

http {
  upstream web_app {
    server web:80;
  }

  upstream api_app {
    server api:3001;
  }

  upstream yjs_server {
    server yws:1234;
  }

  upstream livekit_ws {
    server livekit:7881;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://api_app/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
    }

    location /presence/ {
      proxy_pass http://api_app/presence/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
    }

    location /yjs/ {
      proxy_pass http://yjs_server/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
    }

    location /livekit/ {
      proxy_pass http://livekit_ws/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://web_app/;
      proxy_set_header Host $host;
    }
  }
}
